### ISSUE TITLE
Flash on/off for sprites (when hit by enemy for example)

### ISSUE THREAD

**Issue by Ninjadoodle** [ekelokorpi/panda-editor#24]
**Is your feature request related to a problem? Please describe.**
Feature - add to Essentials :) Flash on/off for sprites (when hit by enemy for example)

**Describe the solution you'd like**
The sprite should flash on/off (visible/invisible), and would be awesome to set the interval

**Describe alternatives you've considered**
I have a manual solution working, but it would be awesome to have a library of effects like this in one place.

**Additional context**
Here is a link to a Construct version of this effect ...
https://www.youtube.com/watch?v=9gS-wYEY_eg

**Comment by ekelokorpi** [comment]
Moved to https://github.com/ekelokorpi/panda-plugins/issues
